=== hmrc/property-business-api/resources/public/api/conf/6.0/schemas/historic_uk_non_fhl_period_summary_create/def1/request.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "title": "Given any tax year",
  "properties": {
    "fromDate": {
      "description": "The first day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD (Our systems only accept dates between 1900-01-01 and 2100-01-01)",
      "type": "string",
      "format": "date",
      "example": "2020-01-01"
    },
    "toDate": {
      "description": "The last day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD (Our systems only accept dates between 1900-01-01 and 2100-01-01)",
      "type": "string",
      "format": "date",
      "example": "2020-01-01"
    },
    "income": {
      "description": "Object containing the details about income",
      "type": "object",
      "properties": {
        "periodAmount": {
          "description": "Total rents from property, ground rents and rent charges but not rent-a-room.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "premiumsOfLeaseGrant": {
          "description": "Premiums received for the grant of a lease and other lump sums to possess a property.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "reversePremiums": {
          "description": "Amount paid by a landlord or outgoing tenant to induce a new tenant to enter into a leasehold agreement.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "otherIncome": {
          "description": "Other income from property, such as rent charges and ground rents, income from letting others tip waste on your land, and income for the use of a caravan or houseboat at a fixed location.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "taxDeducted": {
          "description": "Tax already deducted from the rental income.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "rentARoom": {
          "description": "Objects holding rents received for the period",
          "type": "object",
          "properties": {
            "rentsReceived": {
              "description": "Total rents received from properties.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            }
          }
        }
      }
    },
    "expenses": {
      "description": "Object holding deductions for the period",
      "type": "object",
      "properties": {
        "premisesRunningCosts": {
          "description": "Rent, rates, insurance, ground rents and other costs.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "repairsAndMaintenance": {
          "type": "number",
          "description": "Property repairs and maintenance.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "financialCosts": {
          "description": "Loan interest and other financial costs.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "professionalFees": {
          "description": "Legal, management and other professional fees.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "costOfServices": {
          "description": "Cost of services provided, including wages.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "other": {
          "description": "Other allowable property expenses.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 682.34
        },
        "consolidatedExpenses": {
          "description": "The sum of all allowable expenses for the specified period. You can either submit a consolidatedExpenses value or individual expenses (premisesRunningCosts, repairsAndMaintenance, financialCosts, professionalFees, costOfServices, other, travelCosts, residentialFinancialCostsCarriedForward, residentialFinancialCost, rentARoom).\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "travelCosts": {
          "description": "Car, van and travel costs incurred in running a property business.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "residentialFinancialCostsCarriedForward": {
          "description": "Amount of residential financial costs carried forward.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 5000.99
        },
        "residentialFinancialCost": {
          "description": "Captures residential financial cost that can be deductible from rental income (tax relief). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01,
          "example": 1000.45
        },
        "rentARoom": {
          "description": "Object holding the amount claimed for the period",
          "type": "object",
          "properties": {
            "amountClaimed": {
              "type": "number",
              "description": "The amount of UK Furnished Holiday Lettings rent claimed.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            }
          }
        }
      }
    }
  },
  "required": [
    "fromDate",
    "toDate"
  ]
}

=== hmrc/property-business-api/resources/public/api/conf/6.0/examples/historic_uk_non_fhl_period_summary_create/def1/request.json
{
  "fromDate": "2019-03-11",
  "toDate": "2020-04-23",
  "income": {
    "periodAmount": 123.45,
    "premiumsOfLeaseGrant": 2355.45,
    "reversePremiums": 454.56,
    "otherIncome": 567.89,
    "taxDeducted": 234.53,
    "rentARoom": {
      "rentsReceived": 567.56
    }
  },
  "expenses":{
    "premisesRunningCosts": 567.53,
    "repairsAndMaintenance": 324.65,
    "financialCosts": 453.56,
    "professionalFees": 535.78,
    "costOfServices": 678.34,
    "other": 682.34,
    "travelCosts": 645.56,
    "residentialFinancialCostsCarriedForward": 672.34,
    "residentialFinancialCost": 1000.45,
    "rentARoom": {
      "amountClaimed": 545.9
    }
  }
}
