=== hmrc/property-business-api/resources/public/api/conf/6.0/schemas/uk_property_period_summary_create/def1/request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "For TY 2023-24 and before",
  "description": "This endpoint allows the developer to submit the income and expenses for a foreign property business that occurred between two dates. This submission is for either or both of Furnished Holiday Lettings (FHL) in the European Economic Area (EEA) and all other foreign Property submissions. A National Insurance number and business ID are required.",
  "type": "object",
  "properties": {
    "fromDate": {
      "description": "The first day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD (Our systems only accept dates between 1900-01-01 and 2100-01-01)",
      "type": "string",
      "format": "date",
      "example": "2020-01-01"
    },
    "toDate": {
      "description": "The last day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD (Our systems only accept dates between 1900-01-01 and 2100-01-01)",
      "type": "string",
      "format": "date",
      "example": "2020-01-31"
    },
    "ukFhlProperty": {
      "description": "Object  holding the income and expenses of the UK property business.\n(At least one of income or expenses should be present)",
      "type": "object",
      "properties": {
        "income": {
          "description": "Object holding the income details for the period.",
          "type": "object",
          "properties": {
            "periodAmount": {
              "description": "Total rents from property, ground rents and rent charges but not rent-a-room. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "taxDeducted": {
              "description": "The tax deducted from the income. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "rentARoom": {
              "description": "Object holding the rents received for the period.",
              "type": "object",
              "properties": {
                "rentsReceived": {
                  "description": "Total rents received from properties. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "minimum": 0,
                  "maximum": 99999999999.99,
                  "multipleOf": 0.01,
                  "example": 5000.99
                }
              },
              "additionalProperties": false
            }
          }
        },
        "expenses": {
          "description": "Object holding the expenses for the period.",
          "type": "object",
          "properties": {
            "premisesRunningCosts": {
              "description": "Rent, rates, insurance, ground rents and other costs. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "repairsAndMaintenance": {
              "description": "Property repairs and maintenance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "financialCosts": {
              "description": "Loan interest and other financial costs. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "professionalFees": {
              "description": "Legal, management and other professional fees. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "costOfServices": {
              "description": "Cost of services provided, including wages. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "travelCosts": {
              "description": "Car, van and travel costs incurred in running a property business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "other": {
              "description": "Other allowable property expenses. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "rentARoom": {
              "description": "Object holding the amount claimed for the period.",
              "type": "object",
              "properties": {
                "amountClaimed": {
                  "description": "The amount of UK Furnished Holiday Lettings rent claimed.The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "minimum": 0,
                  "maximum": 99999999999.99,
                  "multipleOf": 0.01,
                  "example": 5000.99
                }
              }
            },
            "consolidatedExpenses": {
              "type": "number",
              "description": "The sum of all allowable expenses for the specified period. You can either submit a consolidatedExpenses value or individual expenses (premisesRunningCosts, repairsAndMaintenance, financialCosts, professionalFees, costOfServices, other, travelCosts, rentARoom). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            }
          },
          "additionalProperties": false
        }
      }
    },
    "ukNonFhlProperty": {
      "description": "Object  holding the income and expenses of the UK property business - excluding Furnished Holiday Lettings (FHL) for the period. (At least one of income or expenses should be present)",
      "type": "object",
      "properties": {
        "income": {
          "description": "Object holding the income details for the period.",
          "type": "object",
          "properties": {
            "premiumsOfLeaseGrant": {
              "description": "Premiums received for the grant of a lease and other lump sums to possess a property. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "reversePremiums": {
              "description": "Amount paid by a landlord or outgoing tenant to induce a new tenant to enter into a leasehold agreement. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "periodAmount": {
              "description": "Total rents from property (but not ground rents, rent charges and rent-a-room rental income). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "taxDeducted": {
              "description": "Tax already deducted from the rental income. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "otherIncome": {
              "description": "Other income from property, such as rent charges and ground rents, income from letting others tip waste on your land, and income for the use of a caravan or houseboat at a fixed location. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "rentARoom": {
              "description": "Object holding the rents received for the period.",
              "type": "object",
              "properties": {
                "rentsReceived": {
                  "description": "Total rents received from properties.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "minimum": 0,
                  "maximum": 99999999999.99,
                  "multipleOf": 0.01,
                  "example": 5000.99
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        },
        "expenses": {
          "description": "Object holding the expenses for the period.",
          "type": "object",
          "properties": {
            "premisesRunningCosts": {
              "description": "Rent, rates, insurance, ground rents and other costs. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "repairsAndMaintenance": {
              "description": "Property repairs and maintenance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "financialCosts": {
              "description": "Loan interest and other financial costs. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "professionalFees": {
              "description": "Legal, management and other professional fees. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "costOfServices": {
              "description": "Cost of services provided, including wages. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "other": {
              "description": "Other allowable property expenses. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "residentialFinancialCost": {
              "description": "The residential financial cost deductible from rental income (tax relief). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "travelCosts": {
              "description": "Car, van and travel costs incurred in running a property business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "residentialFinancialCostsCarriedForward": {
              "description": "Amount of residential financial costs carried forward. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            },
            "rentARoom": {
              "description": "Object holding the amount claimed for the period.",
              "type": "object",
              "properties": {
                "amountClaimed": {
                  "description": "The amount of UK Furnished Holiday Lettings rent claimed. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "minimum": 0,
                  "maximum": 99999999999.99,
                  "multipleOf": 0.01,
                  "example": 5000.99
                }
              }
            },
            "consolidatedExpenses": {
              "type": "number",
              "description": "The sum of all allowable expenses for the specified period. You can either submit a consolidatedExpenses value or individual expenses (premisesRunningCosts, repairsAndMaintenance, financialCosts, professionalFees, costOfServices, other, residentialFinancialCost, travelCosts, residentialFinancialCostsCarriedForward, rentARoom). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "minimum": 0,
              "maximum": 99999999999.99,
              "multipleOf": 0.01,
              "example": 5000.99
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "fromDate",
    "toDate"
  ]
}

=== hmrc/property-business-api/resources/public/api/conf/6.0/examples/uk_property_period_summary_create/def1/consolidated_request.json
{
  "fromDate": "2021-04-06",
  "toDate": "2021-07-05",
  "ukFhlProperty":{
    "income": {
      "periodAmount": 5000.99,
      "taxDeducted": 3123.21,
      "rentARoom": {
        "rentsReceived": 532.12
      }
    },
    "expenses": {
      "consolidatedExpenses": 988.18
    }
  },
  "ukNonFhlProperty": {
    "income": {
      "premiumsOfLeaseGrant": 42.12,
      "reversePremiums": 84.31,
      "periodAmount": 9884.93,
      "taxDeducted": 842.99,
      "otherIncome": 31.44,
      "rentARoom": {
        "rentsReceived": 947.66
      }
    },
    "expenses": {
      "consolidatedExpenses": 988.18
    }
  }
}
